package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CommitteeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommitteeAllPropertiesEquals(Committee expected, Committee actual) {
        assertCommitteeAutoGeneratedPropertiesEquals(expected, actual);
        assertCommitteeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommitteeAllUpdatablePropertiesEquals(Committee expected, Committee actual) {
        assertCommitteeUpdatableFieldsEquals(expected, actual);
        assertCommitteeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommitteeAutoGeneratedPropertiesEquals(Committee expected, Committee actual) {
        assertThat(expected)
            .as("Verify Committee auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommitteeUpdatableFieldsEquals(Committee expected, Committee actual) {
        assertThat(expected)
            .as("Verify Committee relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommitteeUpdatableRelationshipsEquals(Committee expected, Committee actual) {
        // empty method
    }
}
