package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PositionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPositionAllPropertiesEquals(Position expected, Position actual) {
        assertPositionAutoGeneratedPropertiesEquals(expected, actual);
        assertPositionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPositionAllUpdatablePropertiesEquals(Position expected, Position actual) {
        assertPositionUpdatableFieldsEquals(expected, actual);
        assertPositionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPositionAutoGeneratedPropertiesEquals(Position expected, Position actual) {
        assertThat(expected)
            .as("Verify Position auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPositionUpdatableFieldsEquals(Position expected, Position actual) {
        assertThat(expected)
            .as("Verify Position relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPositionUpdatableRelationshipsEquals(Position expected, Position actual) {
        // empty method
    }
}
